/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Integer.parseInt;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Anoni
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public FormPrincipal() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAbrirTotalmente = new javax.swing.JButton();
        FecharTotalmente = new javax.swing.JButton();
        txtAbrir = new javax.swing.JTextField();
        lblAbrir = new javax.swing.JLabel();
        txtFechar = new javax.swing.JTextField();
        lblFechar = new javax.swing.JLabel();
        btnEnviarA = new javax.swing.JButton();
        btnEnviarF = new javax.swing.JButton();
        lblEstadoTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxPorta = new javax.swing.JComboBox();
        lblPorcento = new javax.swing.JLabel();
        lblPorcento2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnSobre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controles"));

        btnAbrirTotalmente.setText("Abrir Totalmente");
        btnAbrirTotalmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirTotalmenteActionPerformed(evt);
            }
        });

        FecharTotalmente.setText("Fechar Totalmente");
        FecharTotalmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharTotalmenteActionPerformed(evt);
            }
        });

        lblAbrir.setText("Abrir Porcentualmente:");

        lblFechar.setText("    Fechar Porcentualmente:");

        btnEnviarA.setText("Enviar");
        btnEnviarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarAActionPerformed(evt);
            }
        });

        btnEnviarF.setText("Enviar");
        btnEnviarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarFActionPerformed(evt);
            }
        });

        lblEstadoTitulo.setText("Última Ação da Válvula:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Porta:");

        cbxPorta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPorcento.setText("%");

        lblPorcento2.setText("%");

        lblEstado.setText("---");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEstadoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorcento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnviarA)
                                .addGap(18, 18, 18)
                                .addComponent(btnAbrirTotalmente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFechar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorcento2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnviarF)
                                .addGap(18, 18, 18)
                                .addComponent(FecharTotalmente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FecharTotalmente, btnAbrirTotalmente});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAbrir, txtFechar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbrir)
                    .addComponent(txtAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarA)
                    .addComponent(lblPorcento)
                    .addComponent(btnAbrirTotalmente)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechar)
                            .addComponent(txtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPorcento2)
                            .addComponent(btnEnviarF)
                            .addComponent(FecharTotalmente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSobre.setText("Sobre");
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Válvula Computadorizada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSobre)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnSobre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirTotalmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirTotalmenteActionPerformed
        Controlador ct = new Controlador(9600, cbxPorta.getSelectedItem().toString());
        ct.comunicacao("A");
        lblEstado.setText("Totalmente Aberto.");
    }//GEN-LAST:event_btnAbrirTotalmenteActionPerformed

    private void FecharTotalmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharTotalmenteActionPerformed
      
        Controlador ct = new Controlador(9600, cbxPorta.getSelectedItem().toString());
        ct.comunicacao("F");
        lblEstado.setText("Totalmente Fechado.");
    }//GEN-LAST:event_FecharTotalmenteActionPerformed

    private void btnEnviarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarAActionPerformed
     
        if(txtAbrir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entrada vazia.");
        }
        else{
            if (parseInt(txtAbrir.getText()) > 0 && parseInt(txtAbrir.getText()) < 100){
                    Controlador ct = new Controlador(9600, cbxPorta.getSelectedItem().toString());
                    ct.comunicacao("a" + parseInt(txtAbrir.getText()));
                    lblEstado.setText(txtAbrir.getText() + "% Aberto.");
        }
            else{
                   lblEstado.setText("---"); 
            }
        }
        txtAbrir.setText("");
    }//GEN-LAST:event_btnEnviarAActionPerformed

    private void btnEnviarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarFActionPerformed
               
        if(txtFechar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entrada vazia");
        }
        else{
            if(parseInt(txtFechar.getText()) > 0 && parseInt(txtFechar.getText()) < 100){
                Controlador ct = new Controlador(9600, cbxPorta.getSelectedItem().toString());
                ct.comunicacao("f" + parseInt(txtFechar.getText()));
                lblEstado.setText(txtFechar.getText() + "% Fechado.");
            }
            else
                lblEstado.setText("---");
        }        
        txtFechar.setText("");
    }//GEN-LAST:event_btnEnviarFActionPerformed

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        FormSobre fs = new FormSobre();
        
        fs.setVisible(true);
    }//GEN-LAST:event_btnSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FecharTotalmente;
    private javax.swing.JButton btnAbrirTotalmente;
    private javax.swing.JButton btnEnviarA;
    private javax.swing.JButton btnEnviarF;
    private javax.swing.JButton btnSobre;
    private javax.swing.JComboBox cbxPorta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAbrir;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblPorcento;
    private javax.swing.JLabel lblPorcento2;
    private javax.swing.JTextField txtAbrir;
    private javax.swing.JTextField txtFechar;
    // End of variables declaration//GEN-END:variables

private void configurarFormulario(){
    
    alterarIcone();
    
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    lblEstado.setEnabled(false);
    
    cbxPorta.setModel(new DefaultComboBoxModel());
    cbxPorta.addItem("COM1");
    cbxPorta.addItem("COM2");
    cbxPorta.addItem("COM3");
    cbxPorta.addItem("COM4");
    cbxPorta.addItem("COM5");
    cbxPorta.addItem("COM6");
    cbxPorta.addItem("COM7");
    cbxPorta.addItem("COM8");
    cbxPorta.addItem("COM9");
    
}

public void alterarIcone(){
        URL url = this.getClass().getResource("/Imagens/valve.png");  
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(imagemTitulo);   
    }

}
